export const ATTR_BUBBLE_USER = 'data-gpth-toggle-bubble-user'
export const ATTR_BUBBLE_GPT = 'data-gpth-toggle-bubble-gpt'
export const ATTR_BUBBLE_USER_ACCENT = 'data-gpth-toggle-bubble-user-accent'
export const ATTR_CHATBOX_HEIGHT = 'data-gpth-toggle-chatbox-height'
export const ATTR_HIDE_HEADER = 'data-gpth-hide-header'
export const ATTR_HIDE_FOOTER = 'data-gpth-hide-footer'
export const ATTR_HIDE_UPGRADE_CHIP = 'data-gpth-hide-upgrade-chip'
export const ATTR_ACCENT_TEXT = 'data-gpth-toggle-accent-text'
